# Generated by Django 3.1 on 2020-08-30 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 28, 1, 813977), verbose_name='date published'),
        ),
    ]
